name: build
on:
  push: { branches: [main] }
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { path: cgbum-repo }
      - uses: actions/checkout@v4
        with: { repository: keiyoushi/extensions-source, path: extensions-source, fetch-depth: 1 }
      - run: |
          rm -rf extensions-source/src/id/cgbum extensions-source/src/id/magadaxx
          cp -a cgbum-repo/src/id/cgbum extensions-source/src/id/cgbum
          cp -a cgbum-repo/src/id/magadaxx extensions-source/src/id/magadaxx
          cp cgbum-repo/signingkey.jks extensions-source/signingkey.jks
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: gradle/actions/setup-gradle@v4
        with: { gradle-version: "8.10.2" }
      - working-directory: extensions-source
        env:
          KEY_STORE_PASSWORD: cgbum123
          ALIAS: cgbum
          KEY_PASSWORD: cgbum123
        run: ./gradlew :src:id:cgbum:assembleRelease :src:id:magadaxx:assembleRelease --stacktrace
      - uses: actions/upload-artifact@v4
        with: { name: cgbum-apk, path: extensions-source/src/id/cgbum/build/outputs/apk/release/*.apk }
      - uses: actions/upload-artifact@v4
        with: { name: magadaxx-apk, path: extensions-source/src/id/magadaxx/build/outputs/apk/release/*.apk }
